import time
from pathlib import Path

from app.models.schemas import OutputFormat
from app.services.engines.base_engine import ReconstructionEngine


class MockReconstructionEngine(ReconstructionEngine):
    name = "mock"
    is_implemented = True

    def __init__(self, delay_seconds: int = 5) -> None:
        self.delay_seconds = max(delay_seconds, 0)

    def is_available(self) -> bool:
        return True

    def reconstruct(
        self,
        project_id: str,
        images_dir: Path,
        output_dir: Path,
        output_format: OutputFormat,
    ) -> Path:
        # Simula tiempo de reconstruccion para poder probar la app end-to-end.
        time.sleep(self.delay_seconds)

        image_count = len([path for path in images_dir.iterdir() if path.is_file()]) if images_dir.exists() else 0
        output_dir.mkdir(parents=True, exist_ok=True)
        model_filename = f"{project_id}_model.{output_format.value}"
        model_path = output_dir / model_filename

        if output_format == OutputFormat.OBJ:
            model_path.write_text(
                "\n".join(
                    [
                        "# Simulated OBJ generated by MockReconstructionEngine",
                        f"# project_id={project_id}",
                        f"# images={image_count}",
                        "o MockObject",
                        "v 0.0 0.0 0.0",
                        "v 1.0 0.0 0.0",
                        "v 0.0 1.0 0.0",
                        "f 1 2 3",
                    ]
                ),
                encoding="utf-8",
            )
        else:
            model_path.write_bytes(
                (
                    "SIMULATED_GLB\n"
                    f"project_id={project_id}\n"
                    f"images={image_count}\n"
                    "Replace MockReconstructionEngine with a real pipeline."
                ).encode("utf-8")
            )

        return model_path
